[package]
name = "lateralizador"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
pnet = "0.31"
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"
lazy_static = "1.4"